### ISSUE TITLE
malware making in c++

### ISSUE THREAD

**Issue by achallion** [ORCA666/hacking-books#1]
hey i want to start create malware in c++ and want to go to expert level in that
can you guide for so or give atleast a good book for that

**Comment by ORCA666** [comment]
@achallion  we all have been there, my best advise to u is to get these 2 books that are talking about windows system programming (thats if ur already familiar with c/cpp) , and the antivirus hacker handbook .

next u gotta do some researches, specially at first,  look for some simple things, simple techs, dont rush in, even if it is getting detected, if u opened a shell using ur own code, ur doing something.
try using normal injection techs, dont bypass av, evade sandbox ....  just mess around with the code, learn from it, what api its using, there is tons of samples here, u can start with eva, u can for example take the find_pid file and analyze it, maybe youll need a function to get the pid of a running process in the future ...
then try using simple codes, samples, libraries from here on github . (search for process hollowing for example, and try to perform it , or dll injection, hijacking ... )
even if these seems  old, and they are, new neat code will always work, then move on developing a second version of what are u doing, (for if u used createprocess next version u can add syscalls and use ntopenprocess , or add api hashing or do api hooking)
a quick tip : follow some security pages on social media to know new ideas, new techs, and learn from it, or work ur code the same way ...
there is no such thing as a book to code malware, if there were, it will be a disaster, malware are just codes, it do something it shouldn't do, i code such things for fun, and i love showing what i can do . 

finish the first 2 steps then u can mail me, i would love to see ur code :D 
- btw malware have feelings -

**Comment by achallion** [comment]
Haha malware has feelings thats why they like if we focus on them
Thanks For Help
I will start it asap
Also will they lead me also to making malware for android too >?

**Comment by ORCA666** [comment]
> Haha malware has feelings thats why they like if we focus on them
> Thanks For Help
> I will start it asap
> Also will windows malwares lead me also to making malware for android too >?

nop, windows is a whole different os, however , and since windows 11 will be able to run android apps , if u wanna learn both u can learn java for android and thus building for android is building for windows 11. but thats a different deal

**Comment by achallion** [comment]
OKee i got it
 Thank you
